### ISSUE TITLE
Which is the correct naming for onloaded?

### ISSUE THREAD

**Issue by t0mm13b** [Chevtek/angular-spinners#14]
There's a reference to both 'onLoaded' and 'on-loaded'. 

Which is the correct one to use?

**Comment by AlexAllocated** [comment]
In Angular it is a convention that directive attributes use the hyphen in markup.

``` html
<spinner name="mySpinner" on-loaded="spinnerLoaded()"></spinner>
```

There is a section showing usage here: https://github.com/codetunnel/angular-spinners#onloaded
