### ISSUE TITLE
ng-repeat not registering all spinners

### ISSUE THREAD

**Issue by zatchgordon** [Chevtek/angular-spinners#20]
I'm trying to create 4 divs on a page each loading their own content so I put the spinner inside the ng-repeat each with the same group name so I can hideGroup if need be. 

After loading and trying to hideGroup only the last spinner in the ng-repeat gets hidden

**Comment by AlexAllocated** [comment]
Do all the spinners in the repeat have the same name? Every spinner must have a unique name. They can all be part of the same group but they must have unique names.

**Comment by zatchgordon** [comment]
They either had the same name or no name. 
They all were in the same group.

I don't have the code any more because I've gone in a different direction.

But thank you. That was probably the problem. I should have put an $index in the name so they would have a unique name.

**Comment by AlexAllocated** [comment]
No worries. Sorry it took so long for me to respond. I didn't have notifications on this repo setup properly and haven't been back here in a while.
